### PR TITLE
Task 1 

### PR DESCRIPTION
**Pull request by ESE-MONDAY**
Added Ese.md to content folder
added ese.jpg to asset folder

### CODE REVIEW

**Comment by kenny-io** [comment]
Hi @ESE-MONDAY good job on this PR, just one thing to fix, your image is broken. Please move it to the `src/public/assets` folder

**Comment by ESE-MONDAY** [comment]
Hi Kenny, it's currently in the src/public/asset folder, should i move it to public/asset folder?

**Comment by kenny-io** [comment]
> Hi Kenny, it's currently in the src/public/asset folder, should i move it to public/asset folder?

Yes please! thank you

**Comment by ESE-MONDAY** [comment]
I just did, please review it. Thanks for the assistance

**Pull request merged**
