### PR TITLE
Add Gorretti Maduabuchi profile to cohort three

### PR DESCRIPTION
**Pull request by Mgorretti**

### CODE REVIEW

**Comment by kenny-io** [comment]
@Mgorretti great job putting the PR together!

Just one thing, your image is in the wrong folder.

Move it from `src/assets/image.jpg` to `public/assets/image.jpg`

**Comment by Mgorretti** [comment]
Move src/assests/Gorretti.jpg to public/assests/Gorretti.jpg

**Comment by Mgorretti** [comment]
move src/assets/Gorretti.jpg to public/assets/Gorretti.jpg

**Comment by kenny-io** [comment]
Great work on this PR @Mgorretti I will update it directly now!

**Pull request closed without merging**
