### PR TITLE
Akshat: Cohort 3 profile

### PR DESCRIPTION
**Pull request by akshatvirmani**

### CODE REVIEW

**Comment by kenny-io** [comment]
Great job on this PR @akshatvirmani 
I noticed that you deleted the `joshua.md` file, good thinking there (we will remove it eventually), but I would like to keep it for now to serve as a guide for other mentees. Please add it back and update your PR

**Comment by akshatvirmani** [comment]
Hi!
Okay, Will do

**Comment by kenny-io** [comment]
@akshatvirmani thanks for the quick fix! the main branch is 1 commit ahead of your PR now, would you mind pulling the new changes into your branch before sending the PR to avoid conflicts

**Comment by akshatvirmani** [comment]
Okay, Will do!

**Pull request closed without merging**
