### PR TITLE
add Arafat Olayiwola to the cohort-three board

### PR DESCRIPTION
**Pull request by Horlawhumy-dev**
Kindly review my PR. Thanks

### CODE REVIEW

**Review by kohasummons — APPROVED** [review]
Good One, @Horlawhumy-dev!

**Comment by kenny-io** [comment]
@Horlawhumy-dev Well done on this PR! It came fast and mostly worked as expected. The only issue is that your image is broken. 
image
I noticed that your image is in `src/assets/` consider moving it into `public/assets` directory to make it globally available to `.md` files.

**Comment by Horlawhumy-dev** [comment]
Thanks for the notice @kenny-io. 
Pushed the changes

**Review by kenny-io — CHANGES_REQUESTED** [review]
@Horlawhumy-dev thank you for the updated PR. We have some updates in main that you haven't pulled into your branch yet. 
In addition, the content directory has changes, so your file will no longer be in `src/content/cohort/arafat.md` but in `src/content/cohort-3/arafat.md`.

**Comment by kenny-io** [comment]
Great work @Horlawhumy-dev closed by #90

**Pull request closed without merging**
