### PR TITLE
Feat: add geoffreylogovi profile to cohort three

### PR DESCRIPTION
**Pull request by geoffreylgv**
## What did I do:
- [x] Update my branch as the origin [Dxmentorship](https://github.com/Dxmentorship/dxmentorship)
- [x] Add my image profile
- [x] Create my name Markdown file and update by filling it with my informations
- [x] Updates changes, commit and push to create the PR

### CODE REVIEW

**Comment by kenny-io** [comment]
@geoffreylgv great job on this PR, it looks great! there's a small conflict in `.astro/types.d.ts` pls fix and resend your PR

**Comment by geoffreylgv** [comment]
> @geoffreylgv great job on this PR, it looks great! there's a small conflict in `.astro/types.d.ts` pls fix and resend your PR

All right

**Comment by geoffreylgv** [comment]
> @geoffreylgv great job on this PR, it looks great! there's a small conflict in `.astro/types.d.ts` pls fix and resend your PR

Hi @kenny-io, PR updated

**Comment by kenny-io** [comment]
Great work @geoffreylgv

**Comment by geoffreylgv** [comment]
> Great work @geoffreylgv

Thank you @kenny-io , I really appreciate it.

**Pull request merged**
